### ISSUE TITLE
Speeds different on different viewports

### ISSUE THREAD

**Issue by archiewood** [abosch19/svelte-fast-marquee#1]
Cool component, thanks! 

Seems to run much faster on small viewports than desktop.

Maybe there's a good workaround here, but I'd love it if it felt "similar" on mobile to desktop

**Comment by 3200pro** [comment]
I agree. I'm not sure how to slow it down on mobile. It's unreadable.

**Comment by 3200pro** [comment]
Looks like there is a speed prop you can use. It still is based on the viewport size so it speeds up on mobile but it'll be readable. 

Ex: `<Marquee pauseOnHover speed="30">`

**Comment by archiewood** [comment]
I was hoping for something that would give me speed "parity".

I've slowed it down on mobile but now on desktop it's soooo slow

**Comment by 3200pro** [comment]
> I was hoping for something that would give me speed "parity".
> 
> I've slowed it down on mobile but now on desktop it's soooo slow

Same... but better than waaaayyy to fast.

I wonder if two marquees would be warranted. One visible for mobile and another for desktop.

**Comment by abosch19** [comment]
Hi guys, thank you for creating creating this issue.

I think it happens by the wrong calculation of pixel speed, I'll fix it and publish today.

Regards

**Comment by abosch19** [comment]
@archiewood @3200pro published version 0.5.0. Check pls if its working correctly. I also added a prop `gardient` to show a gradient on the edges.

Thank you for all <3

**Comment by archiewood** [comment]
This works great, live on our website: www.evidence.dev
