### ISSUE TITLE
Error: Marquee is not a valid SSR component

### ISSUE THREAD

**Issue by zaxwebs** [abosch19/svelte-fast-marquee#4]
Error: <Marquee> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise 
you may need to fix a <Marquee>.

**Comment by abosch19** [comment]
Hi @zaxwebs,

I'll check the build process and I'm going to release a new version this weekend. 

Thank you

**Comment by abosch19** [comment]
Hi @zaxwebs,

I can't reproduce this behaviour you mentioned before, can you give me more information?
- Are you using the last version?
-  Can you share me your project to see it?

Thank you

**Comment by zaxwebs** [comment]
I am currently using a copy of Marquee.svelte and it works.

- Are you using the last version? Yes
- Can you share me your project to see it? Unfortunately not.

But we can mark this as closed, I will try the latest version.
